### PR TITLE
Add important symlinks for Play 2.3

### PR DESCRIPTION
**Pull request by mkurz**
Adds symlinks for the `plugin` and the `samples` folder inside the `play23` folder.
This is very important otherwise the plugin itself for Play 2.3 doesn't get compiled and also the tests for 2.3 would not run.

I also fixed some sbt warnings because of the upgrade to sbt 0.13.15.

### CODE REVIEW

**Comment by mkurz** [comment]
@mumoshu
FYI: I have a working version of play2-memcached with Play 2.6-RC2 on my machine already :tada:   However it needs some more work. I will wait until 2.6 final before I submit the pull request.

**Comment by mkurz** [comment]
@mumoshu Can you please merge and release a new version (for Play 2.5) ? I will hopefull start to work on 2.6 support soon.

**Comment by mumoshu** [comment]
@mkurz Thanks for your contribution 👍

**Comment by mkurz** [comment]
@mumoshu Thanks, I am working on support for Play 2.6 right now!

**Pull request merged**
