### PR TITLE
Scala 2.13

### PR DESCRIPTION
**Pull request by mkurz**
@mumoshu please also publish for Scala 2.13, thanks!

### CODE REVIEW

**Comment by mkurz** [comment]
@mumoshu Can you merge and release a new version (that is also build for Scala 2.13?) I already added `0.10.1` to the README... :wink:

**Comment by mkurz** [comment]
Thanks!

**Comment by mkurz** [comment]
@mumoshu Looking forward having this published :wink:

**Comment by jtjeferreira** [comment]
@mumoshu any chance to have this published?

**Comment by mkurz** [comment]
+1
@mumoshu 0.10.1 isn't published yet: https://repo1.maven.org/maven2/com/github/mumoshu/

**Comment by mumoshu** [comment]
Ah sorry, I thought I've published it 3 weeks ago via sbt-sonatype. I'll take a look asap.

**Comment by mumoshu** [comment]
I believe I've managed to publish 0.10.0 for 3 scala versions which is now available via the maven central.

**Pull request merged**
