### PR TITLE
Support for Play 2.7.0-M1

### LINKED ISSUE #60: Current builds not compatible with play 2.7 milestone 1
Play framework released their first milestone for play 2.7, 2.7-M1.

I tried upgrading a project that uses memcached, but it failed to run.

This is the output I got:

```
! @78dd9o295 - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[NoClassDefFoundError: play/api/cache/CacheApi]
at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:189)
at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:124)
at play.core.server.netty.PlayRequestHandler.handle(PlayRequestHandler.scala:84)
at play.core.server.netty.PlayRequestHandler.channelRead(PlayRequestHandler.scala:177)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at com.typesafe.netty.http.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:129)
at com.typesafe.netty.http.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:96)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: play/api/cache/CacheApi
at com.github.mumoshu.play2.memcached.MemcachedModule$$anonfun$$lessinit$greater$1.apply(MemcachedModule.scala:61)
at com.github.mumoshu.play2.memcached.MemcachedModule$$anonfun$$lessinit$greater$1.apply(MemcachedModule.scala:20)
at play.api.inject.SimpleModule.bindings(Module.scala:88)
at play.api.inject.guice.GuiceableModuleConversions.guice(GuiceInjectorBuilder.scala:340)
at play.api.inject.guice.GuiceableModuleConversions.guice$(GuiceInjectorBuilder.scala:339)
at play.api.inject.guice.GuiceableModule$.guice(GuiceInjectorBuilder.scala:274)
at play.api.inject.guice.GuiceableModuleConversions$$anon$3.$anonfun$guiced$2(GuiceInjectorBuilder.scala:319)
at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
at scala.collection.immutable.List.foreach(List.scala:389)
at scala.collection.TraversableLike.map(TraversableLike.scala:234)
at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
at scala.collection.immutable.List.map(List.scala:295)
at play.api.inject.guice.GuiceableModuleConversions$$anon$3.guiced(GuiceInjectorBuilder.scala:319)
at play.api.inject.guice.GuiceableModule$.$anonfun$guiced$1(GuiceInjectorBuilder.scala:296)
at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
at scala.collection.immutable.List.foreach(List.scala:389)
at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
at scala.collection.immutable.List.flatMap(List.scala:352)
at play.api.inject.guice.GuiceableModule$.guiced(GuiceInjectorBuilder.scala:296)
at play.api.inject.guice.GuiceBuilder.createModule(GuiceInjectorBuilder.scala:171)
at play.api.inject.guice.GuiceApplicationBuilder.applicationModule(GuiceApplicationBuilder.scala:111)
at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:186)
at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:139)
at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
at play.core.server.DevServerStart$$anon$1.$anonfun$reload$3(DevServerStart.scala:173)
at play.utils.Threads$.withContextClassLoader(Threads.scala:22)
at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:165)
… 35 common frames omitted
Caused by: java.lang.ClassNotFoundException: play.api.cache.CacheApi
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
… 63 common frames omitted
Stopping Play…
```

When asked on play framework's forum, it was stated that the version of the dependency wasn't compatible: https://discuss.lightbend.com/t/play-2-7-0-m1-released/1380/10

Is the time right now for compiling a version for milestone 1 so it can be tested, or is it better to wait for the full release?

### PR DESCRIPTION
**Pull request by mkurz**
First milestone release of Play 2.7.0 is out.
Fixes #60

### CODE REVIEW

**Comment by mkurz** [comment]
@mumoshu This should be ready to merge. I named the version `0.10.0-M1`, we can remove `-M1` when Play 2.7 is released.

**Comment by Ottunger** [comment]
@mkurz Planning to merge this one anytime soon? I wished it reached maven already.

**Comment by mkurz** [comment]
Pinging @mumoshu

**Comment by mumoshu** [comment]
@mkurz Thanks a lot for your effort, as always! LGTM.

> This is getting more and more a mess here...

Definitely... You seem to be the most active play2-memcached user. Would you mind if I renamed the current master to e.g. `legacy` and remove all the things related to older verions of Play, so that all we need to support becomes the latest release of Play.

**Comment by mkurz** [comment]
@mumoshu See #62 - no work for you anymore :smile:

**Comment by jtjeferreira** [comment]
any chance of releasing `0.10.0-M1` for early testing?

**Comment by mumoshu** [comment]
@jtjeferreira Hey! I've published ones for 0.10.0-M2 today. Would those work for you? Do you still need M1?

**Comment by jtjeferreira** [comment]
`0.10.0-M2` is perfect!

**Comment by hayd** [comment]
Play 2.7.0 is released!

**Comment by mkurz** [comment]
See #72

**Pull request merged**
