### PR TITLE
Play 2.7.0-RC3 and sbt upgrade

### PR DESCRIPTION
**Pull request by mkurz**
Upgrades to Play 2.7.0-RC3 :tada: 

Also upgrades sbt to 1.2.x - which mean I had to finally migrate `project/Build.scala` to `build.sbt`. (They are very similar however, I cleaned it up a bit).

BTW: Play 2.7.0-RC3 wasn't released for Scala 2.13 yet. That will happen in a future version.

### CODE REVIEW

**Comment by mkurz** [comment]
RC3 has been officially released now: https://discuss.lightbend.com/t/play-2-7-0-rc3-released/2715

**Comment by mkurz** [comment]
Added two more commits.
@mumoshu Looking forward to your review :wink:

**Comment by mkurz** [comment]
Ping @mumoshu (Please also merge #67, thanks)

**Comment by mumoshu** [comment]
Im now releasing this for Scala 2.11.12.. Thanks for patience

```
PLAY_VERSION=2.7.0-RC8 sbt ++2.11.12 publishSigned sonatypeRelease
```

**Comment by mumoshu** [comment]
```
[error] (scala-sample / publishConfiguration) Repository for publishing is not specified.
[error] (java-sample / publishConfiguration) Repository for publishing is not specified.
[error] (publishConfiguration) Repository for publishing is not specified.
[error] Total time: 57 s, completed 2018/11/30 11:18:11
```

**Comment by mumoshu** [comment]
And for 2.12.7 too.

```
PLAY_VERSION=2.7.0-RC8 sbt ++2.12.7 sonatypeRelease
```

**Comment by mumoshu** [comment]
Done publishing.

**Comment by mkurz** [comment]
Please git-tag the releases, thanks! Maybe we can use https://github.com/sbt/sbt-release in future which can automatically publish and then tag the releases...

**Pull request merged**
