### PR TITLE
Play 2.8

### PR DESCRIPTION
**Pull request by mkurz**
Also switched to AdoptOpenJDK

### CODE REVIEW

**Comment by mkurz** [comment]
@mumoshu This pull request can be merged, Play 2.8 got released. Time to release `0.11.0` :wink: (Be aware that I added `-SNAPSHOT` to the version in `build.sbt`, so yo probably want to change that before releasing)

**Comment by jamesward** [comment]
Pretty please :)

**Comment by mkurz** [comment]
@mumoshu Can you please also release version 0.11.0, looks like it wasn't cut yet: https://repo1.maven.org/maven2/com/github/mumoshu/
Thanks!

**Comment by mumoshu** [comment]
Forgot to leave a notice for that but I believe I've published corresponding releases for this a few days ago. Please poke me if they arent available yet :)

**Comment by mkurz** [comment]
@mumoshu Thanks, looks good!
https://repo1.maven.org/maven2/com/github/mumoshu/play2-memcached-play28_2.13/
https://repo1.maven.org/maven2/com/github/mumoshu/play2-memcached-play27_2.13/

**Comment by hayd** [comment]
Is it possible to tag this release on GitHub too? Thanks!

**Pull request merged**
