### PR TITLE
Add support for Play 2.9 and Scala 3 :tada: 

### PR DESCRIPTION
**Pull request by mkurz**

### CODE REVIEW

**Comment by mkurz** [comment]
@mumoshu Travis CI does not work anymore. I can set up GitHub actions if that is ok for you? I can do that in a next pull request.
BTW: All tests pass locally on my machine.

**Comment by mkurz** [comment]
@mumoshu Also is it possible that you rename the `master` branch to `main`, you can do that in the Settings page of this GitHub repo.

**Comment by mkurz** [comment]
@mumoshu can you take a look?

**Review by mumoshu — APPROVED** [review]
LGTM. Thank you very much for your continuous support and contribution @mkurz ❤️

**Pull request merged**
